const db  = require('./index.js');
const Bike = require('./bike.js');

const simpleData = [
    {
        model: "Kids Bike", 
        price:"" ,
        imageUrl: "https://i1.adis.ws/i/washford/193694?w=740&h=555&qlt=75&fmt=webp&v=1",
        description: " Wheel is the perfect bike for kids that still need to build their confidence on two wheels! Its grown-up cream colour and butterfly graphics will make learning to ride a bike loads of fun. Safety is also in mind, with removable stabilisers, and a full chainguard that will protect fingers and clothes from getting caught in the chain. The front and rear caliper brakes will also ensure that your little one will always have plenty of control when riding.",
        
    },
      {
        model: "Adult Bike",
        price:"" ,
        imageUrl: "https://i5.walmartimages.com/asr/3ed1be16-2c88-408a-ad27-a4a3a19bfc25_1.7b1544aab1d8c637638560fa44b6c71b.jpeg?odnWidth=612&odnHeight=612&odnBg=ffffff",
        description: "Ride with confidence and style on the Meridian tricycle by Schwinn. This full-sized tricycle for adults is perfect for those who want to enjoy the outdoors. The Meridian?s stylish three-wheeled design provides more stability than a bicycle, while the step-through aluminum frame provides a low stand over height, making it easier to get on and off. Its single-speed drivetrain, front linear pull brake, and rear drum brake make it simple to use. Plus, this tricycle?s upright riding position and cruiser dual spring saddle make it a joy to ride. And don?t forget - the rear folding basket has plenty of room for cargo, like a backpack, bags of groceries, and more. (Note: the basket is not suitable for children, pets, or other passengers.) Experience the joy of cycling like never before with the Meridian tricycle. Enjoy the freedom of riding a Schwinn.",
        daysOfService: "0",
    },  
    {
        model: "Track Bike",
        price:"" ,
        imageUrl: "https://www.bikeinn.com/f/13762/137623423/se-bikes-ripper-x-20-2020.jpg",
        description: "Built with a super-stiff 6066 aluminum frame featuring a bi-oval downtube and 6066 aluminum Landing Gear forks, this rad ride weighs in at a featherweight 16.5 pounds. Rounding out the package are Alienation Ankle Biter rims, a Promax Impact Mini stem and new Vee Tire Co Speed Booster tires. It’s no wonder that the Ripper X is one of the fastest rippers on the track.",
        daysOfService: "0",
    },  
    {
        model: "Kids Bike",
        price:"" ,
        imageUrl: "https://i1.adis.ws/i/washford/193694?w=740&h=555&qlt=75&fmt=webp&v=1",
        description: " Wheel is perfect for tackling off road trails. with its 6 speed gearing riding hills are no problem and with alloy break levers you are assured firstopping power after you race back down.",
        daysOfService: "0",
    },
      {
        model: "City Bike",
        price:"" ,
        imageUrl: "https://www.bikeinn.com/f/13762/137624787/fuji-traverse-1.5-2020.jpg",
        description: "The Traverse is a dual-sport machine that will take you anywhere. With disc brakes, the Traverse is a confident commuter on city streets but still able to conquer trails with ease.",
        daysOfService: "0",
    },
      {
        model: "City Bike",
        price:"" ,
        imageUrl: "https://www.bikeinn.com/f/13762/137624795/fuji-declaration-2020.jpg",
        description: "Whether you´re a professional messenger, an urban shredder or a school or work commuter, the Declaration is made to divide and conquer all that the city streets bring.",
        daysOfService: "0",
    },
    {
        model: "Cyclocross Bike",
        price:"" ,
        imageUrl: "https://www.bikeinn.com/f/13759/137593968_3/factor-o2-disc.jpg",
        description: "The O2 has been shaped and constructed for the best performance on the road, not just on the test lab. After long hours spent on FEA for structural analysis and perfecting the carbon fibre layup in our factory, many frames and fork samples in all sizes were made to be tested on the road by our team of test riders, as well as some of the top professional cyclists. This extended road testing provided very valuable feedback to refine and perfect the riding characteristics of the Factor O2.",
        daysOfService: "0",
    },
    {
        model: "City Bike",
        price:"" ,
        imageUrl: "https://www.bikeinn.com/f/13755/137553325/ghost-square-trekking-6.8-al-w.jpg",
        description: "With the SQUARE TREKKING line, we demonstrate that a puristically reduced bike can be extremely resilient on the one hand and extremely versatile on the other. Smart solutions, such as the hub dynamo or a spring flap on the luggage carrier as well as the comfortable contact points will convince the long-distance riders in particular. The stylish, simple frame with almost invisibly laid lines and its seamlessly integrated fenders are pure eye candy for design lovers. And for those of you for whom all of this is not yet enough, the well thought-out geometry will be convincing - absolutely comfortable and extremely smooth. SQUARE Trekking - squaring the circle.",
        daysOfService: "0",
    },
    {
        model: "Mountain Bike",
        price:"" ,
        imageUrl: "https://outdoorgearlab-mvnab3pwrvp3t0.stackpathdns.com/photos/22/96/351096_3421_L2.jpg",
        description: "The Ibis Ripmo was updated for 2020, and the V2 is indeed an improvement over the original. The primary changes, including a degree slacker head tube angle, a longer wheelbase, and a more progressive suspension curve may seem subtle, but the result is an even more well-rounded ride with enhanced composure on descents and improved stability at speed. The Ripmo has no downhill speed or terrain limits, yet it still magically climbs like a bike with less travel and tackles technical terrain with the best of them. The geometry feels perfectly dialed and it excels both up and down the mountain. The DW-Link suspension handles the 147mm of rear-wheel travel well with excellent mid-stroke support and improved big hit performance. Our testers were absolutely blown away by the new Ripmo, and we feel this is the best trail bike we've tested.",
        daysOfService: "0",
    },
    {
        model: "Trick Bike",
        price:"" ,
        imageUrl: "https://www.bikeinn.com/f/13762/137623446/se-bikes-gadium-20-2020.jpg",
        description: "If you’ve ever seen Kris Fox ride, you know that he needs a bike that can keep up with his incredible speed and insane heights. And his signature Gaudium does just that. This stylish bike features a double-butted main frame, female axle hubs, Alienation rims, extra-wide 2.4” tires, and Odyssey pedals. It’s built to blast and take any abuse you can throw at it.",
        daysOfService: "0",
    },
    {
        model: "Trick Bike",
        price:"" ,
        imageUrl: "https://images-na.ssl-images-amazon.com/images/I/71wwxwwWoCL._AC_SL1500_.jpg ",
        description: "Withstand the tough of the sand, snow or road with ease. Durable 6061 Aluminum alloy frame together with the full suspension fork, offers smooth cushioning and shock absorption when cycling on rough terrains. Enjoy the excitement during your ride.",
        daysOfService: "0",
    },
    {
        model: "Mountain Bike",
        price:"" ,
        imageUrl: "https://outdoorgearlab-mvnab3pwrvp3t0.stackpathdns.com/photos/19/77/319226_7308_L2.jpg",
        description: "Ibis recently released the 4th iteration of their popular Ripley trail bike with many notable changes from the previous version. They took some cues from the instant success of the longer travel Ripmo and incorporated many of its design features into the new design of its shorter travel sibling. It still features 120mm of rear and 130mm of front wheel travel, but its wheelbase and reach have been extended significantly while the head tube has been slackened and the seat tube steepened. The Ripley is still one of the most fun and playful trail bikes in this review and climbs and descends better than its predecessor. The GX Eagle build we tested is well appointed and shred ready straight out of the box. If you're looking for a short travel trail bike, we don't think it gets much better than the new Ibis Ripley. ",
        daysOfService: "0",
    },
    {
        model: "Mountain Bike",
        price:"" ,
        imageUrl: "https://outdoorgearlab-mvnab3pwrvp3t0.stackpathdns.com/photos/21/92/340713_25027_L2.jpg",
        description: "The 2020 YT Jeffsy Base 29 is the hands-down winner of our Editor's Choice award for the best mountain bike under $2500. It slides right back into the top spot, replacing the 2019 version on the top of the podium, but with 10mm more travel front and rear and an updated modern progressive geometry. This 29er now sports 150mm of travel and a longer and slacker geometry that makes it even more hard-charging on the descents while still retaining its solid climbing abilities, versatility, and well-rounded trail manners. It also comes with a spectacular component specification for the price that helps inspire confidence and enhance its overall performance. The Jeffsy Base 29 is a great trail bike and a truly outstanding one at this price. ",
        daysOfService: "0",
    },
    {
        model: "Mountain Bike",
        price:"" ,
        imageUrl: "https://outdoorgearlab-mvnab3pwrvp3t0.stackpathdns.com/photos/21/59/337447_19833_L2.jpg",
        description: "The only thing tougher than reaching the top is staying there, a feat the 2020 Specialized Turbo Levo Comp has achieved after winning a third consecutive Editor's Choice Award. Enhanced to keep its reputation as the best electric-assist mountain bike on the market, the 2020 model now includes a quieter, more powerful 90NM Brose drive motor with 560 peak watts of output and a bigger 700Wh battery boosting range by 40 percent over its predecessor. The 2020 Turbo Levo carries over the 2019 model year geometry tweaks and the stiffened 'sidearm' design of the Stumpjumper for better climbing, descending and overall handling performance. Whether going for a quick after-work lap or gunning for a big, 'gnar-mega' day in the backcountry, the added power and range of the 2020 Turbo Levo Comp is up to the task. This is easily the most refined and best all-around e-bike we've ever tested.",
        daysOfService: "0",
    },
    {
        model: "Hybrid Bike",
        price:"" ,
        imageUrl: "https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/2/2019/04/Carrera-Subway-1-1-920x613.jpg",
        description: "Admittedly, it’s not quite as comfortable as some other options out there, so if you’re going on long adventures we’d recommend that you look elsewhere.",
        daysOfService: "0",
    },  {
        model: "Hybrid Bike",
        price:"" ,
        imageUrl: "https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/2/2020/05/CONTINUUM_NEW_LIGHT_CORRECTED-3-920x613.jpg",
        description: "The Priority Bicycles Continuum Onyx includes front and rear lights, fenders, and uses a Gates Carbon belt drive system with a continuously variable rear hub. It’s unlike most anything on the market and offers the advantage of reduced maintenance and no chance of grease on your clothes. Gearing covers a similar range as a 1×8 drivetrain but without distinct gears. It’s smooth and easy to start from a stop.",
        daysOfService: "0",
    },
    {
        model: "Hybrid Bike",
        price:"" ,
        imageUrl: "https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/2/2019/06/Screen-Shot-2020-01-28-at-14.00.35.png",
        description: "A speedy tarmac bike which will suit those commuting mostly on the road. The carbon fork is phenomenal value and adds an enormous amount of comfort to the ride The newest models come under the Triban name. In this case with disc brakes and a compact 50/34 chainset boasting a rear cassette replete with a wide spread of gears.It’s a popular bike and, as a Decathlon exclusive brand, can sometimes be tricky to get hold of.",
        daysOfService: "0",
    },
    {
        model: "Road Bike",
        price:"" ,
        imageUrl: "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1588105694-giant-tcr-advanced-sl-0-disc-1588105677.jpg?crop=1xw:1xh;center,top",
        description: "Giant’s premier race bike gets a full redesign for model year 2021. The frame is 140 grams lighter which helps the top of the line model shown here alight our scale at just 14.5 pounds (size large)—impressive for a bike with power meter, disc brakes, and 42mm-deep tubeless-ready wheels. And even though it weighs less, Giant added some aerodynamic tuning to reduce drag for greater efficiency. The new TCR embraces the trend toward wider tires with clearance for up to 32mm-wide rubber. The build reflects the price: SRAM Red eTap AXS with power meter, carbon bar and stem, and a Cadex (a Giant brand) wheelset with carbon rims and carbon spokes. On the road, this bike is very quick and handles extremely well.",
        daysOfService: "0",
    },
    {
        model: "Road Bike",
        price:"" ,
        imageUrl: "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1588105122-triban-rc520-1588105106.jpg?crop=1xw:1xh;center,top",
        description: "Triban is a house brand of Decathlon, a France-based sporting goods chain. The RC 520 is a value-priced endurance bike with a slightly upright position, a longer wheelbase for stability, great tire clearance (up to 36mm), and provisions for attaching racks and fenders. This model has a smooth shifting Shimano 105 11-speed drivetrain with compact gearing (11-32 cassette with 50/34 chainrings). The disc brakes are TRP’s HY/RD, which is a cable actuated hydraulic brake that offers impressive performance. Decathlon backs the frame, handlebar, and stem with a lifetime warranty. We found this bike is not only a great value, it’s a great ride. This is a smooth and versatile bike that’s well suited to both paved and mild dirt-road riding.",
        daysOfService: "0",
    },
    {
        model: "Road bike",
        price:"" ,
        imageUrl: "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1580753152-cannondale-caad13-105-1580753137.jpg?crop=0.947xw:0.704xh;0.0256xw,0.264xh",
        description: "We’ve loved Cannondale’s aluminum frames because they offer outstanding performance for a reasonable price. Cannondale carries that legacy forward with the faster and more refined CAAD 13. The latest CAAD has some aerodynamic tuning to save watts. 30mm tire clearance (disc models), and shares geometry with Cannondale’s SuperSix carbon race bike. It’s not all business—the new CAAD has hidden fender mounts too.",
        daysOfService: "0",
    },
    {
        model: "Triathlon/Time Trial Bike",
        price:"" ,
        imageUrl: "https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/2/2017/03/full_speedmax-cf-slx-9-ltd_c1329-920x518.png",
        description: "The entry level model enjoys a carbon frame, built around a Shimano 105 frame with Mavic Cosmic Elite hoops. The cockpit features the Canyon H30 Basebar Flat CF.As you move through the range, the cockpit becomes even more sophisticated, with greater integration and more storage space, ideal for long distance events.",
        daysOfService: "0",
    },
    {
        model: "Triathlon/Time Trial Bike",
        price:"" ,
        imageUrl: "https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/2/2019/04/XELA5001-1507038167-920x636.jpg",
        description: "The geometry is designed for UCI WorldTour level pros, and is super agressive, with plenty of aero nods, such as the shaped seat tube and integrated front end plus a ‘NACA’ (National Advisory Committee for Aeronautics) airfoil shape to the handlebar – though we’d like to see the level of external cabling reduced in time.",
        daysOfService: "0",
    },
    {
        model: "Triathlon/Time Trial Bike",
        price:"" ,
        imageUrl: "https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/2/2019/04/97419-00_SHIV-SW-DISC-DI2-LTD-SNST-FIVE-O-WHT_HERO-920x568.jpg",
        description: "The redesigned Shiv from Specialized has been fine tuned specifically for triathlon, and is now 60 seconds quicker than the UCI legal Shiv.The fin at the back holds water, with Ironman length races at front of mind. To make travel easier, the bars fold by simply loosening five bolts.",
        daysOfService: "0",
    },
    {
        model: "Triathlon/Time Trial Bike",
        price:"" ,
        imageUrl: "https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/2/2013/06/Cervelo-P5-2016-bike-630x420.jpg",
        description: "To a competitive rider, where every watt counts this can be significant though. Top spec groupsets, such as SRAM eTap and Shimano Dura Ace help reduce weight, giving top end machines a slight weight advantage over mid price bikes. Electronic groupsets are often found on top end models. Great examples of top spec time trial and triathlon bikes are the Canyon Speedmax CF SLX and Cervélo P5.",
        daysOfService: "0",
    },
    {
        model: "Commuting Bike",
        price:"" ,
        imageUrl: "https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/2/2020/08/Sheso-920x613.jpg",
        description: "With a flash ‘Gloss Hyper Green’ paint job, Specialized Sirrus hybrid is made the brand’s A1 Alloy butted aluminum and is the perfect commuting companion. The bike rolls on 700c wheels so it will cover ground with haste, and with room for 42mm wide tires, rough roads and dirt paths challenge the resolve of your hands or posterior. There are rack and fenders mounts on the dropped seat stays and the fork, and there are bosses for two bottles inside the main triangle. For those who are vertically challenge, there is a step through version too.",
        daysOfService: "0",
    },
    {
        model: "Commuting Bike",
        price:"" ,
        imageUrl: "https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/2/2020/06/Pinnacle-Lithium-3-2020-920x606.jpg",
        description: "With an aluminum frame sporting both mudguard and pannier mounts, the Lithium 3 ticks two major boxes for a versatile commuter bike. The Tektro hydraulic disc brakes provide powerful and modulated braking even in wet conditions, whilst the 3×8 drivetrain offers sufficient gears for even the steepest of hills.",
        daysOfService: "0",
    },
    {
        model: "Commuting Bike",
        price:"" ,
        imageUrl: "https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/2/2020/06/Carrera-Subway-1-dark.jpg  ",
        description: "At a slightly more budget friendly price point, the Carrera Subway 1 also offers 24 gears and disc brakes. However, hydraulics are sacrificed here in favor of cheaper mechanical disc brakes. These don’t have quite the same power and modulation as a hydraulic system, but still perform better in the wet than traditional rim brakes.",
        daysOfService: "0",
    },
    {
        model: "Womens Bike",
        price:"" ,
        imageUrl: "https://i1.adis.ws/i/washford/566700?w=740&h=555&qlt=75&fmt=webp&v=1",
        description: "The Apollo Excelle Womens Hybrid Bike features 18-speed Shimano gearing and steel v-brakes which offers controlled riding experience. A sturdy steel construction means the Excelle is easy to maintain and ride and also features lightweight 700c wheels for fast acceleration with smoother tyres for more comfortable riding on both roads and park trails. ",
        daysOfService: "0",
    },
    {
        model: "Womens Bike",
        price:"" ,
        imageUrl: "https://i1.adis.ws/i/washford/507530?w=740&h=555&qlt=75&fmt=webp&v=1",
        description: "The Pendleton Somerby Hybrid Bike is the personification of style coupled with a classic design. The classic step-through frame to make hopping on and off easy, the beautiful Somerby has a sprung leather-style saddle for comfort with 7 speed Shimano gearing to help you up hills.",
        daysOfService: "0",
    },
    {
        model: "Womens Bike",
        price:"" ,
        imageUrl: "https://i1.adis.ws/i/washford/566320?w=740&h=555&qlt=75&fmt=webp&v=1",
        description: "Apollo has gained a reputation for manufacturing quality bikes that offer exceptional value for money, and the Apollo Twilight certainly ticks both of these boxes. Mixing solid build quality with premium components, you’ll get plenty of bang for your buck with an Apollo Twilight Womens Mountain Bike.",
        daysOfService: "0",
    },
]

const insertSampledata = function() {
    Bike.create(simpleData)
      .then(() => db.disconnect());
  };
  
  insertSampledata();